### ISSUE TITLE
Multiple instances with the same database.

### ISSUE THREAD

**Issue by sgdc3** [LordAkkarin/Stockpile#1]
In order to bypass the MojangApi request limit is it possible to use multiple instances of stockpile?
Thanks ;)

**Comment by dotStart** [comment]
Technically I'd say "Yes" as the application does not actually store any data locally. Practically I haven't tested this feature yet (which is why it isn't part of the manual).

TL;DR: Go for it. There's a 90% chance it will work just fine! :)

**Comment by sgdc3** [comment]
Thank you.
Just thought about that, how to load-balance the request between the instances?

**Comment by dotStart** [comment]
You will most likely need another application to handle this. Something among the lines of nginx or haproxy (Technically any kind of round robin would work too but assuming you are running Stockpile in your local network, you will probably not have that luxury).

**Comment by Yive** [comment]
Looks like I can retire my old broken caching system for this & run 68 instances of it
