### ISSUE TITLE
Redis as NoSql database

### ISSUE THREAD

**Issue by sgdc3** [LordAkkarin/Stockpile#2]
Would it be possible to use NoSql database like redis?

**Comment by dotStart** [comment]
No. Only SQL based databases are supported at the moment as Hibernate currently handles data storage. In addition only PostgreSQL and H2 have been actively tested.

**Comment by dotStart** [comment]
I'll mark this as an enhancement for consideration later.

**Comment by dotStart** [comment]
This issue will be tracked in #4 along with a set of otherwise relevant implementations (Currently targeted for 1.1.0 ... I'm not sure when I'll have time to work on that release though).

Lots of GitHub spam! Yey!
