### ISSUE TITLE
Error 500 using mysql

### ISSUE THREAD

**Issue by sgdc3** [LordAkkarin/Stockpile#6]
``` xml
<Map xmlns="">
<timestamp>1466086953711</timestamp>
<status>500</status>
<error>Internal Server Error</error>
<exception>
org.springframework.dao.InvalidDataAccessApiUsageException
</exception>
<message>
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.torchmind.stockpile.server.entity.DisplayName.profile -> com.torchmind.stockpile.server.entity.Profile; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.torchmind.stockpile.server.entity.DisplayName.profile -> com.torchmind.stockpile.server.entity.Profile
</message>
<path>/v1/name/sgdc3</path>
</Map>
```

**Comment by sgdc3** [comment]
Using mysql-connector-java-5.1.37 and Stockpile 1.0.0 release

**Comment by dotStart** [comment]
Pastebin the error log please.

**Comment by sgdc3** [comment]
http://hastebin.com/fuxaqetefa.xml
No errors in console.

**Comment by sgdc3** [comment]
Ah, you mean this log xD, sorry
http://hastebin.com/opodudevuc.vala

**Comment by dotStart** [comment]
Just one question: How did you manage to get Stockpile to run on a MySQL server? Technically it's not even supported (in fact I don't even include a driver for it).

**Comment by sgdc3** [comment]
Just manually shaded the mysql connector, i didn't know it doesn't support mysql :/

**Comment by dotStart** [comment]
Officially it doesn't (due to licensing restrictions and wah wah wah). Practically it should work though. I'll give it a look later.

**Comment by sgdc3** [comment]
Can't you download the connector on a lib folder only if the user accept a license agreement?

**Comment by sgdc3** [comment]
It would bypass the license restriction as you are not providing the library inside your executable

**Comment by dotStart** [comment]
No longer applicable.
